enum FormStatus {
  FORM_STATUS_UNSPECIFIED,
  FORM_STATUS_DRAFT,
  FORM_STATUS_PUBLISHED,
  FORM_STATUS_ARCHIVED,
}

enum FormFieldType {
  FORM_FIELD_TYPE_UNSPECIFIED,
  FORM_FIELD_TYPE_TEXT,
  FORM_FIELD_TYPE_TEXTAREA,
  FORM_FIELD_TYPE_NUMBER,
  FORM_FIELD_TYPE_EMAIL,
  FORM_FIELD_TYPE_PHONE,
  FORM_FIELD_TYPE_DATE,
  FORM_FIELD_TYPE_TIME,
  FORM_FIELD_TYPE_DATETIME,
  FORM_FIELD_TYPE_SELECT,
  FORM_FIELD_TYPE_MULTI_SELECT,
  FORM_FIELD_TYPE_RADIO,
  FORM_FIELD_TYPE_CHECKBOX,
  FORM_FIELD_TYPE_TOGGLE,
  FORM_FIELD_TYPE_RATING,
  FORM_FIELD_TYPE_PHOTO,
  FORM_FIELD_TYPE_SIGNATURE,
  FORM_FIELD_TYPE_LOCATION,
  FORM_FIELD_TYPE_BARCODE,
}
